def complementingDNA(DNA):
    pairs = {
        'A':'T',
        'T':'A',
        'G':'C',
        'C':'G'
    }
    complemental = ''
    for base in DNA:
        complemental += pairs[base]
    reverse = complemental[::-1]
    print(reverse)

complementingDNA('CGCGCCCTCACAGACTGCTTCCGCGCAAGCCACTACCCGGTGGCGCGTGCGAGTACACACAATGGTCAACCACGGGTTGATACATTCGACTAAGACTTAATTCACAAGTCTCGTGCGACGGGCTCACAGCCCAATCTGATTCGATGTTCTCAGTTCGTATGGTATTCCTTGAGGAATAGGGGACAGTACATCGTGGTCTCCATAACTTGAGTCGTCGGTCCCAAATCGTTTACGATTCTGTAGCCGTTGAGCTAATAGAGTCGTTTACACCCCAGGCACCACTAGGGCTCTCGCGGGCTATCGTAATTCTTGTGCATTAACACGGAGTCCTGCGGTCCTTGGACGTGCAAATCTAAACCATGCTCTTAATTTCATTGTATACATTGCTTCTTAACGTATACGCTATACCTTACCTGTCGCCACGGTGGCAAAGCTTCATACCCGTCCTGAGAGTCCGACATTGTATGGCATTCCAAGAGATGTGGGAGGGCTCAGGGAAGTCTATTCCAAACCCAATAAGTGTACAGAAGTTGAGCAAAGGAGTAAGCTAGAAGTTCTCAGATCCTCCGCCATACATACTATCCCTAAGTCGCTCCCATTGGTTCGTCGTCGCGCCGGGAGCGCCACACTACGCTTCGGATAATTCTAGCACAAAAGGAGAAGAAGGTCGTCCTGGAAAAATCGTGGCAGCCTCGGCCTCTGCTCATCACGGAACCAGGGCGCAAAGTTCTGAGGATCAAACTTCCTGACGTACTATGCCAAAGCCAGGAGGATATCCGCGGAGTTACGAGGTTGCGAAGTTCCACATGTCGCTCTGAATCAGCGTTGGAGGAATGTTACATGCGCGTAGTACAGCCATGTTGACACTGCAAACACAAACATTAAAATGAGCGCACGAATCTTTCAAGTGCTCGACAACCTTATATATTTCC')