def findMotif(s, t):
    start_index = 0
    t_index_list = [ ]
    while start_index < len(s):
        t_index = s.find(t, start_index)
        if t_index == -1:
            break
        print(t_index + 1, end=' ')
        start_index = t_index + 1

findMotif('CGGGCTTTACTGGCTTTAGGGCTTTAAATGAGGCTTTAGAGGGCTTTAACGGCTTTAAGGCTTTACGGCTTTAGGCTTTAGGCTTTAATATAAGGCTTTAGTTGGCTTTATGGGGTTGGCTTTAAGGCTTTAGTAGGCTTTAAGGCTTTAGGGGCTTTAACGGCTTTAGGCTTTATGGCTTTATGGCTTTAGGCTTTATAAGGCTTTAAGGCTTTAAGGCTTTATGGCTTTACTTAGGCTTTAGGCTTTACGCAGATATGGCTTTAGGCTTTACTTAGCCTCGGCTTTACTGGCTTTAGCCTGGCTTTAGGCTTTATATGCTAGGCTTTAGACTGCCAGGCTTTAACGGCTTTACCGGCTTTATCTGGCTTTAGGGCTTTAAAGGCTTTACGGGCTTTACCCGCTCGCATTCGGGCTTTAGGCTTTAGGCTTTAGGCTTTAGGCTTTAGGCTTTACGGGCTTTAACTTGAGGCTTTAGACTCATCCGGCTTTAGGCCATGATTAGGCTTTAGGCTTTAGGCTTTATAACTCTCCCCTGGCTTTACGGCTTTAGAAGGCTTTAAAGCAGCCGAGGCTTTAAGTGTAGGCTTTACTCGGCTTTAACTGTGGCTTTATGGACTCGGCTTTAGGAACGCTATGGCTTTACAAAGTGCCGGGCTTTAGGGTGGTGGCTTTAAGGGTGGGATTGGCTTTAGGCTTTAGGCTTTAGATGTCGGCTTTAAATGTGTCGGGGCTTTAAAAAAGGCACTCGGCTTTAACAAACTTGCTGGCTTTACTGAGGCTTTAGGCTTTATTGAGGCTTTAAGGCTTTACAGTCCGCGGCTTTAGGCTTTATG','GGCTTTAGG')